/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.CadastroUsuarioController;
import Controllers.GerenciamentoUsuarioController;
import DAO.UsuarioDAO;
import Models.Usuario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Csarp
 */
public class GerenciaUsuariosView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public GerenciaUsuariosView() {
        initComponents();
        
        
        
        
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Senha = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Editar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("@Cluwt");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 450, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(403, 0, 31, 28);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gerência dos Usuários:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(6, 40, 428, 51);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eita, hora de tirar e adicionar permissão!");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 97, 434, 18);

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuário", "Senha"
            }
        ));
        tabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 420, 180);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel7.setText("Usuário:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, -1));

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usuario.setBorder(null);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Senha.setBorder(null);
        jPanel3.add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, -1));

        label.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        label.setText("ID:");
        jPanel3.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, -1));

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel9.setText("Senha:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 330, 270, 120);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel2.add(Editar);
        Editar.setBounds(290, 410, 130, 30);

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(290, 333, 130, 30);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(290, 370, 130, 30);

        jButton1.setText("Atualizar Tabela de Usuários");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 470, 410, 60);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(320, 500, 70, 20);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 440, 550));

        setSize(new java.awt.Dimension(856, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Configuração da conexão com o banco de dados
        String url = "jdbc:mysql://localhost:3306/sistemarestaurante";
        String usuario = "root";
        String senha = "";

        // Consulta SQL para recuperar os usuários
        String sql = "SELECT * FROM usuarios";

        // Criação do modelo de tabela
        DefaultTableModel modeloTabela = new DefaultTableModel();

        // Configuração das colunas
        modeloTabela.addColumn("ID");
        modeloTabela.addColumn("Usuário");
        modeloTabela.addColumn("Senha");

        try {
            // Conexão com o banco de dados
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            Statement statement = conexao.createStatement();

            // Execução da consulta
            ResultSet resultSet = statement.executeQuery(sql);

            // Preenchimento do modelo de tabela com os dados dos usuários
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String nome = resultSet.getString("username");
                String email = resultSet.getString("password");
                modeloTabela.addRow(new Object[]{id, nome, email});
            }

            // Fechamento dos recursos
            resultSet.close();
            statement.close();
            conexao.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Atribuição do modelo de tabela à JTable
        tabelaUsuarios.setModel(modeloTabela);
    
    }//GEN-LAST:event_formWindowOpened

    private void tabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuariosMouseClicked
                                              
    // Obtém o modelo da tabela
    DefaultTableModel model = (DefaultTableModel) tabelaUsuarios.getModel();
    
    // Obtém o índice da linha clicada
    int rowIndex = tabelaUsuarios.getSelectedRow();
    
    // Verifica se uma linha foi selecionada
    if (rowIndex != -1) {
        // Obtém os valores das colunas da linha selecionada
        int id2 = Integer.parseInt(model.getValueAt(rowIndex, 0).toString()); // Coluna do ID (índice 0)
        String username = model.getValueAt(rowIndex, 1).toString(); // Coluna do username (índice 1)
        String password = model.getValueAt(rowIndex, 2).toString(); // Coluna da senha (índice 2)
        
        // Preenche os campos de Usuario e Senha com os valores obtidos
        id.setText(String.valueOf(id2));
        Usuario.setText(username); // Verifique se este índice está correto
        Senha.setText(password); // Verifique se este índice está correto
    }

    }//GEN-LAST:event_tabelaUsuariosMouseClicked

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
          // Obtém o ID do usuário a ser editado
    int id2 = Integer.parseInt(id.getText());
    
    // Obtém os novos valores do usuário e senha dos campos de texto
    String novoUsuario = Usuario.getText();
    String novaSenha = Senha.getText();
    
    // Cria uma instância do controlador para gerenciar a edição do usuário
    GerenciamentoUsuarioController controller = new GerenciamentoUsuarioController();
    
    // Chama o método para editar o usuário no banco de dados
    if (controller.editarUsuario(id2, novoUsuario, novaSenha)) {
        // Se a edição for bem-sucedida, exiba uma mensagem de sucesso
        JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!");
        // Atualize a tabela de usuários
        atualizarTabelaUsuarios();
    } else {
        // Se a edição falhar, exiba uma mensagem de erro
        JOptionPane.showMessageDialog(null, "Erro ao editar usuário. Verifique os dados e tente novamente.");
    }
    atualizarTabelaUsuarios();
    }//GEN-LAST:event_EditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         UsuarioDAO dao = new UsuarioDAO();
         
         String nomeUsuario = Usuario.getText();
         String senha = Senha.getText();

        try {
            dao.adicionarUsuario(nomeUsuario, senha);
            atualizarTabelaUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciaUsuariosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    UsuarioDAO dao = new UsuarioDAO();
    
    // Supondo que o ID do usuário seja fornecido em um campo de texto chamado "idUsuarioField"
    String idUsuarioTexto = id.getText();
    
    // Verifica se o campo não está vazio
    if (!idUsuarioTexto.isEmpty()) {
        int idUsuario = Integer.parseInt(idUsuarioTexto); // Converte o texto do ID para um inteiro
        dao.excluirUsuario(idUsuario);
        JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
        System.out.println("Usuário excluído com sucesso.");
        atualizarTabelaUsuarios();
        
    } else {
        System.out.println("Por favor, insira o ID do usuário.");
    }
    atualizarTabelaUsuarios();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarTabelaUsuarios();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         AdministradorView AdministradorView = new AdministradorView();
        AdministradorView.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaUsuariosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JTextField Senha;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabelaUsuarios() {
        // Limpa os dados existentes na tabela
    DefaultTableModel model = (DefaultTableModel) tabelaUsuarios.getModel();
    model.setRowCount(0);
    
    // Obtém a lista atualizada de usuários do controlador
    GerenciamentoUsuarioController controller = new GerenciamentoUsuarioController();
    List<Usuario> usuarios = controller.listarUsuarios();
    
    // Preenche a tabela com os novos dados dos usuários
    for (Usuario usuario : usuarios) {
        Object[] rowData = {usuario.getId(), usuario.getUsername(), usuario.getPassword()};
        model.addRow(rowData);
    }
} }
