/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.CadastroUsuarioController;
import Controllers.GerenciamentoPedidosController;
import Controllers.RealizarPedidoController;
import Utils.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import Controllers.RealizarPedidoController;
import DAO.ConexaoDAO;
import DAO.PedidoDAO;
import Models.Pedido;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Csarp
 */
public class RealizarPedidoView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RealizarPedidoView() {
        initComponents();
        RealizarPedidoController controller = new RealizarPedidoController();
        // Popula a combobox de mesas
        controller.popularComboboxMesas(cbOpcao);
        controller.popularComboboxPratos(cbPrato);
        
        
        
        
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbOpcao = new javax.swing.JComboBox<>();
        cbPrato = new javax.swing.JComboBox<>();
        valorTotal = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 450, 350));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("@Cluwt");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(403, 0, 31, 28);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Realização do Pedido:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(6, 40, 428, 51);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vamos ao trabalho!");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 97, 434, 18);

        jLabel7.setText("Mesa:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 180, 40, 30);

        jLabel8.setText("Prato:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 220, 37, 30);

        jButton1.setText("Calcular Total do Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 290, 159, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(40, 370, 160, 23);

        jButton3.setText("Confirmar Pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(40, 330, 160, 23);

        jLabel9.setText("Nome:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(230, 186, 37, 20);

        jLabel10.setText("Valor total:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(240, 310, 80, 30);

        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbOpcao);
        cbOpcao.setBounds(70, 180, 140, 30);

        cbPrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbPrato);
        cbPrato.setBounds(70, 220, 140, 30);

        valorTotal.setEditable(false);
        valorTotal.setBackground(new java.awt.Color(255, 255, 255));
        valorTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorTotal.setBorder(null);
        valorTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(valorTotal);
        valorTotal.setBounds(310, 310, 90, 30);
        jPanel2.add(cliente);
        cliente.setBounds(280, 180, 120, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 160, 420, 110);

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Preço", "Prato", "Mesa"
            }
        ));
        jScrollPane1.setViewportView(tabelaPedidos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 420, 130);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 440, 550));

        setSize(new java.awt.Dimension(856, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    preencherTabelaPedidos(tabelaPedidos);
        

    String mesaSelecionada = (String) cbOpcao.getSelectedItem();
    String pratoSelecionado = (String) cbPrato.getSelectedItem();
    String nomeCliente = cliente.getText();
    
    // Cria uma instância do controlador para calcular o preço total do prato selecionado
    RealizarPedidoController controller = new RealizarPedidoController();
    double precoTotal = controller.calcularPrecoTotal(pratoSelecionado);
    
    // Atribua o valor calculado a valorTotal
    valorTotal.setText(String.valueOf(precoTotal));
    
    // Cria uma instância do DAO para registrar o pedido no banco de dados
    PedidoDAO dao = new PedidoDAO();
    
    try {
        // Registra o pedido no banco de dados
dao.registrarPedido(mesaSelecionada, nomeCliente, pratoSelecionado, precoTotal);
        
    } catch (Exception ex) {
        Logger.getLogger(RealizarPedidoView.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Erro ao registrar pedido: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    preencherTabelaPedidos(tabelaPedidos);
    }//GEN-LAST:event_jButton3ActionPerformed

     public List<Pedido> listarPedidos(Connection conexao) {
    List<Pedido> pedidos = new ArrayList<>();
    String sql = "SELECT id_pedido, nome_cliente, preco_total, nome_prato, numero_mesa FROM pedidos";
    try (PreparedStatement statement = conexao.prepareStatement(sql)) {
        ResultSet resultSet = statement.executeQuery();
        while (resultSet.next()) {
            int idPedido = resultSet.getInt("id_pedido");
            String nomeCliente = resultSet.getString("nome_cliente");
            double precoTotal = resultSet.getDouble("preco_total");
            String nomePrato = resultSet.getString("nome_prato");
            String numeroMesa = resultSet.getString("numero_mesa"); // Alterado para String
            Pedido pedido = new Pedido(idPedido, nomeCliente, precoTotal, nomePrato, numeroMesa);
            pedidos.add(pedido);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return pedidos;
}

       // Método para preencher a tabelaPedidos com os dados da tabela pedidos
    public void preencherTabelaPedidos(JTable tabelaPedidos) {
        // Configuração da conexão com o banco de dados
        String url = "jdbc:mysql://localhost:3306/sistemarestaurante";
        String usuario = "root";
        String senha = "";
        
        // Consulta SQL para recuperar os pedidos
        String sql = "SELECT id_pedido, nome_cliente, preco_total, nome_prato, numero_mesa FROM pedidos";
        
        // Criação do modelo de tabela
        DefaultTableModel modeloTabela = new DefaultTableModel();
        
        // Configuração das colunas
        modeloTabela.addColumn("ID Pedido");
        modeloTabela.addColumn("Nome Cliente");
        modeloTabela.addColumn("Preço Total");
        modeloTabela.addColumn("Nome Prato");
        modeloTabela.addColumn("Número Mesa");
        
        try (Connection conexao = DriverManager.getConnection(url, usuario, senha);
             Statement statement = conexao.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            
            // Preenchimento do modelo de tabela com os dados dos pedidos
            while (resultSet.next()) {
                int idPedido = resultSet.getInt("id_pedido");
                String nomeCliente = resultSet.getString("nome_cliente");
                double precoTotal = resultSet.getDouble("preco_total");
                String nomePrato = resultSet.getString("nome_prato");
                String numeroMesa = resultSet.getString("numero_mesa");
                modeloTabela.addRow(new Object[]{idPedido, nomeCliente, precoTotal, nomePrato, numeroMesa});
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
            // Lidere com qualquer exceção SQL aqui
        }
        
        // Atribuição do modelo de tabela à JTable tabelaPedidos
        tabelaPedidos.setModel(modeloTabela);
    }
     
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    

        // Cria uma instância do controlador de pedidos
        RealizarPedidoController controller = new RealizarPedidoController();

        // Preenche os ComboBoxes com as opções disponíveis
        controller.popularComboboxMesas(cbOpcao);
        controller.popularComboboxPratos(cbPrato);
        
        // Preenche a tabela pedidos:
        preencherTabelaPedidos(tabelaPedidos);
        
        

        
      
        
        

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    preencherTabelaPedidos(tabelaPedidos);

    // Obter o prato selecionado a partir do JComboBox
    String pratoSelecionado = (String) cbPrato.getSelectedItem();
    
    // Cria uma instância do controlador para calcular o preço total do prato selecionado
    RealizarPedidoController controller = new RealizarPedidoController();
    
    // Calcula o preço total do prato selecionado
    double precoTotal = controller.calcularPrecoTotal(pratoSelecionado);
    
    // Formatar o preço total como "R$ xx,xx"
    DecimalFormat df = new DecimalFormat("R$ #,##0.00");
    String precoFormatado = df.format(precoTotal);
    
    // Exibe o preço total formatado no componente valorTotal
    valorTotal.setText(precoFormatado);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AdministradorView AdministradorView = new AdministradorView();
        AdministradorView.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarPedidoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbOpcao;
    private javax.swing.JComboBox<String> cbPrato;
    private javax.swing.JTextField cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
